config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@currency = nil

  	@namecur = CryptoScrap.new.get_name

  	@currency= params[:currency]

  	indice = @namecur.index(@currency).to_i
  

  	@listprice = CryptoScrap.new.get_price

  	@findprice = @listprice[indice]

  	
  end


  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id = "center" class = "w3-card w3-yellow w3-display-middle w3-padding-64 w3-padding-large">

<h1>Crypt0Rails</h1>

<form>
<%= form_tag(home_index_path, method: "get") do |f| %>
    <%= label_tag :curency %><br>
    <%= select_tag :currency, options_for_select(@namecur)  %>
    <%= submit_tag :Submit, :class =>"w3-button w3-black"%>
<% end %>
</form>



<%unless @currency == nil %>
<div class="w3-card w3-red w3-padding-16 w3-padding w3-margin">
<p> Currency :  <%= @currency %></p>
 <p> Price : <%= @findprice %></p>
 </div>
<% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptorails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
  </head>

  <body class = "w3-container w3-black" >
   
    <%= yield %>
  
  </body>
</html>